### ISSUE TITLE
1.12.2: Unable to pick up Mob Spawners despite changing config

### ISSUE THREAD

**Issue by JoshieGemFinder** [BuiltBrokenModding/SBM-cardboardBoxes#11]
I'm using forge version `1.12.2-forge-14.23.5.2855` and `SBM-CardboardBoxes-1.12.2-0.0.2b12.jar` (I believe that's the latest stable version for 1.12.2) in the configs I've set:
```
blacklistsettings {
    # Prevents mobs spawners from being placed into cardboard boxes [default: true]
    B:BlackListMobSpawners=false
}
```
and in `tile_ban_list` I've set:
```
# Clazz[TileEntityMobSpawner] [default: true]
B:"minecraft:mob_spawner"=false
```
any help?

**Comment by DarkGuardsman** [comment]
@GHXX or @bl4ckscor3  can I get you to check into this... as day job has me spent.

**Comment by bl4ckscor3** [comment]
From my testing this fix should have no effect on other cardboard boxes (pre-existing as well as new ones). This is just used to determine the block to place/name to display in addInformation as far as I can tell.

**Comment by bl4ckscor3** [comment]
Tested the fix some more, and found no further issues. Will release a new version now.
