### ISSUE TITLE
Client-Server config issues

### ISSUE THREAD

**Issue by Phonavis** [BuiltBrokenModding/SBM-cardboardBoxes#14]
Version 1.19.x - 0.0.6
Forge 43.1.64 
Minecraft 1.19.2

First issue, the client side config determines what blocks can be picked up, meaning you can just add whatever you want in game on a server.
Second Issue, Client config gets overwritten by server. I'm pretty sure config changes are supposed to stay memory only when syncing, but I have absolutely no understanding of Forge and its config system.

**Comment by Phonavis** [comment]
Third issue, it seems the entire config just gets rewritten on each launch
https://gist.github.com/Scarlet-Phonavis/06fc63747ed8c61d4826d4e402042e38

Here's the config that keeps getting wiped, I double checked all the block names

**Comment by bl4ckscor3** [comment]
1. No, the common config determines what blocks can be picked up, not the client side one. This mod does not have a client side config. The issue you described is a non-issue, as the pick up logic happens entirely server side, meaning if this mod is used in multiplayer, the server's common config will get used to determine what can be picked up. Testing this theory on a server with default config and a client with default config but `minecraft:conduit = false` confirms it.
2. The server config gets synchronized to the client, the common config does not. Hence there is no overwriting taking place. It's just an overruling, as I explained in 1 above. (Further explanation: As server configs are tied to the world you play in, if a server config value is used on client side in a multiplayer server, the config value from the server's server config will be used, as ithosts the one world you play in. )
3. That's a known bug with Forge/Nightconfig, we cannot do anything about that. Close the world/game to prevent it from happening.
